# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [16]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [17]:
f_path = os.path.join("city_data.csv")
cities_df = pd.read_csv(f_path)
cities_df.head()

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,1,severo-kurilsk,50.68,156.12,53.06,68.0,0.0,14.43,RU,1.600049e+09
1,2,port alfred,-33.59,26.89,56.86,64.0,0.0,9.78,ZA,1.600049e+09
2,3,muros,42.78,-9.06,64.00,87.0,100.0,1.99,ES,1.600049e+09
3,4,rikitea,-23.12,-134.97,73.92,84.0,22.0,16.98,PF,1.600049e+09
4,5,faya,18.39,42.45,69.80,17.0,56.0,4.34,TD,1.600049e+09

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [18]:
# create variables to store the data we plan to use on our plot

# data to be used for the plotting coordinates
locations = cities_df[["Lat","Lng"]]

# data to be used to weight the heatmap
rating = cities_df["Humidity"]

# create the mapping figure
fig = gmaps.figure()

# create the heatmap layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating)

# add the heatmap layer to the figure
fig.add_layer(heat_layer)

# display the figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [24]:
#ideal_weather = cities_df[(cities_df["Max Temp"] >= 70) & (cities_df["Max Temp"] <= 80) & (cities_df["Wind Speed"] <= 10) & (cities_df["Cloudiness"] == 0)]
#ideal_weather.head(50)

##should we use the filter method (above) or do I need to drop the rows like below?
cities_df.drop(cities_df[(cities_df["Max Temp"] < 70)].index, inplace = True)
cities_df.drop(cities_df[(cities_df["Max Temp"] > 80)].index, inplace = True)
cities_df.drop(cities_df[(cities_df["Wind Speed"] > 10)].index, inplace = True)
cities_df.drop(cities_df[(cities_df["Cloudiness"] > 0)].index, inplace = True)
cities_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
14,16,bardiyah,31.76,25.09,73.78,77.0,0.0,5.77,LY,1.600049e+09
29,32,elat,29.56,34.95,75.58,56.0,0.0,7.58,IL,1.600049e+09
56,64,uruacu,-14.52,-49.14,72.07,34.0,0.0,3.58,BR,1.600049e+09
92,106,la rioja,42.25,-2.50,71.60,46.0,0.0,4.70,AR,1.600049e+09
152,173,carnarvon,-24.87,113.63,73.40,69.0,0.0,8.05,AU,1.600049e+09
174,199,buraydah,26.33,43.98,78.80,29.0,0.0,2.24,SA,1.600049e+09
191,217,san felipe,10.34,-68.74,75.11,84.0,0.0,3.71,MX,1.600049e+09
195,221,zhuanghe,39.70,122.99,72.61,66.0,0.0,1.81,CN,1.600049e+09
247,279,clarksdale,34.20,-90.57,75.20,100.0,0.0,6.91,US,1.600049e+09
266,299,brazzaville,-4.27,15.28,76.50,62.0,0.0,6.40,CG,1.600049e+09
278,312,olimpia,-20.74,-48.91,78.80,24.0,0.0,8.52,BR,1.600049e+09
313,348,awbari,26.59,12.78,74.79,34.0,0.0,3.94,LY,1.600049e+09
322,357,mabaruma,8.20,-59.78,76.84,84.0,0.0,4.05,GY,1.600049e+09
338,375,platanos,37.67,21.62,78.80,93.0,0.0,2.24,GR,1.600049e+09
353,391,nikolayevsk-na-amure,53.14,140.73,74.73,49.0,0.0,1.97,RU,1.600049e+09
356,394,chabahar,25.29,60.64,78.80,83.0,0.0,9.17,IR,1.600049e+09
365,404,caravelas,-17.71,-39.25,72.23,82.0,0.0,8.75,BR,1.600049e+09
405,445,narrabri,-30.32,149.78,73.99,38.0,0.0,4.70,AU,1.600049e+09
408,448,darab,28.75,54.54,70.65,21.0,0.0,8.25,IR,1.600049e+09
409,449,barra do garcas,-15.89,-52.26,74.39,27.0,0.0,0.85,BR,1.600049e+09
426,468,tabas,33.60,56.92,77.00,20.0,0.0,6.93,IR,1.600049e+09
480,528,gat,31.61,34.76,78.01,100.0,0.0,4.00,LY,1.600049e+09
524,575,moree,-29.47,149.85,77.00,36.0,0.0,5.82,AU,1.600049e+09
528,579,kikwit,-5.04,18.82,76.28,63.0,0.0,2.93,CD,1.600049e+09

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure