# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [43]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [36]:
f_path = os.path.join("city_data.csv")
cities_df = pd.read_csv(f_path)
cities_df.head()

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,bluff,-46.60,168.33,39.99,86.0,71.0,7.00,NZ,1.600190e+09
1,2,bambous virieux,-20.34,57.76,66.20,77.0,75.0,19.46,MU,1.600191e+09
2,3,lebu,-37.62,-73.65,54.25,83.0,97.0,10.65,CL,1.600190e+09
3,4,yabelo,4.88,38.08,69.22,49.0,67.0,12.95,ET,1.600191e+09
4,6,butaritari,3.07,172.79,83.41,75.0,36.0,20.65,KI,1.600190e+09

In [37]:
gmaps.configure(api_key=g_key)

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [39]:
# create variables to store the data we plan to use on our plot

# data to be used for the plotting coordinates
locations = cities_df[["Lat","Lng"]]

# data to be used to weight the heatmap
rating = cities_df["Humidity"]

# create the mapping figure
fig = gmaps.figure()

# create the heatmap layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating)

# add the heatmap layer to the figure
fig.add_layer(heat_layer)

# display the figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [40]:
ideal_weather = cities_df[(cities_df["Max Temp"] >= 70) & (cities_df["Max Temp"] <= 80) & (cities_df["Wind Speed"] <= 10) & (cities_df["Cloudiness"] == 0)].dropna()
ideal_weather.head(50)

##should we use the filter method (above) or do I need to drop the rows like below?
#cities_df.drop(cities_df[(cities_df["Max Temp"] < 70)].index, inplace = True)
#cities_df.drop(cities_df[(cities_df["Max Temp"] > 80)].index, inplace = True)
#cities_df.drop(cities_df[(cities_df["Wind Speed"] > 10)].index, inplace = True)
#cities_df.drop(cities_df[(cities_df["Humidity"] > 50)].index, inplace = True)
#cities_df.drop(cities_df[(cities_df["Cloudiness"] > 0)].index, inplace = True)
#cities_df.reset_index(inplace=True)
#cities_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
14,16,senanga,-16.12,23.27,79.92,15.0,0.0,5.06,ZM,1.600191e+09
249,278,visina,44.58,25.33,79.00,51.0,0.0,6.87,RO,1.600190e+09
297,328,metro,-5.11,105.31,74.10,90.0,0.0,4.76,ID,1.600191e+09
300,331,coalinga,36.14,-120.36,75.99,36.0,0.0,4.45,US,1.600191e+09
303,334,barnbach,47.03,15.85,73.99,70.0,0.0,1.43,AT,1.600191e+09
460,506,dragomiresti,44.92,25.33,78.01,52.0,0.0,6.67,RO,1.600191e+09
540,592,san martin,-33.08,-68.47,73.40,16.0,0.0,5.82,AR,1.600191e+09

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [51]:
#Hotel dataframe
hotel_df = ideal_weather
#Create blank hotel column
hotel_df["Hotel Name"] = ""
#hotel_df

# create a dictionary to contain all URL parameters
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key
}

# Create base API url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# use iterrows to iterate through pandas DataFrame
for index, row in hotel_df.iterrows():

    # get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]

    params["location"] = f"{lat},{lng}"

    # assemble url and make API request
    response = requests.get(base_url, params=params).json()
    
    # extract results
    results = response["results"]
    
    #Add results to the Hotel Name column in the dataframe
    #add try and accept
    try:
        hotel_df.loc[index, "Hotel Name"] = results[0]["name"]
    
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
    #pprint(results[0]["name"])
    
hotel_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
14,16,senanga,-16.12,23.27,79.92,15.0,0.0,5.06,ZM,1.600191e+09,Christopher Nasilele House
249,278,visina,44.58,25.33,79.00,51.0,0.0,6.87,RO,1.600190e+09,Necula Alexandru
297,328,metro,-5.11,105.31,74.10,90.0,0.0,4.76,ID,1.600191e+09,OYO 3177 Wisma Lintang
300,331,coalinga,36.14,-120.36,75.99,36.0,0.0,4.45,US,1.600191e+09,Royal Lodge Motel
303,334,barnbach,47.03,15.85,73.99,70.0,0.0,1.43,AT,1.600191e+09,Wirtshaus Huber
460,506,dragomiresti,44.92,25.33,78.01,52.0,0.0,6.67,RO,1.600191e+09,Casa Licurici
540,592,san martin,-33.08,-68.47,73.40,16.0,0.0,5.82,AR,1.600191e+09,Finca Vivencias

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure